"""The generated reference docs are checked in, and must not drift.

Documentation that is written by hand goes stale the first time a flag
changes; documentation that is generated but not verified goes stale the
first time somebody forgets to run the generator. This closes the second
gap: adding a flag without running `make docs` fails here, in the same run
that added it.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

import tlgr.ops  # noqa: F401  — importing it populates the registry
from tlgr.registry import REGISTRY

ROOT = Path(__file__).resolve().parent.parent
REFERENCE = ROOT / "docs" / "reference"


def test_the_checked_in_reference_matches_the_registry():
    result = subprocess.run(
        [sys.executable, "tools/gen_docs.py", "--check"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr or result.stdout


def test_every_registered_group_has_a_page():
    for group in sorted({spec.group for spec in REGISTRY.values()}):
        assert (REFERENCE / f"{group}.md").exists(), group


def test_the_index_and_the_parity_page_exist():
    assert (REFERENCE / "README.md").exists()
    assert (REFERENCE / "PARITY.md").exists()


@pytest.mark.parametrize("spec", sorted(REGISTRY.values(), key=lambda s: s.id), ids=lambda s: s.id)
def test_every_operation_is_documented(spec):
    page = (REFERENCE / f"{spec.group}.md").read_text(encoding="utf-8")
    assert f"### `{spec.cli_path}`" in page
    assert spec.example_args in page


def test_the_pages_say_they_are_generated():
    for path in REFERENCE.glob("*.md"):
        assert path.read_text(encoding="utf-8").startswith("<!-- Generated by")
