"""tlgr wire models. `from tlgr.models import Message, Page` works."""

from __future__ import annotations

from tlgr.models.base import UNSET, Model, Request, Unset, decode, encode, to_builtins
from tlgr.models.dialog import Dialog, Draft, Folder, NotifySettings
from tlgr.models.envelope import ErrEnvelope, Meta, OkEnvelope, OpRequest
from tlgr.models.error import ErrorBody
from tlgr.models.event import EventEnvelope
from tlgr.models.message import (
    Button,
    ComposeResult,
    DeleteResult,
    DiceCatalog,
    EditResult,
    Effect,
    EntityReport,
    FactCheck,
    Forward,
    ForwardedMessage,
    GameInfo,
    GameScore,
    LinkResult,
    MediaKind,
    MediaSummary,
    Message,
    MessageEntity,
    PaidMessageSettings,
    PinResult,
    ReactionSummary,
    ReactResult,
    ReadReceipts,
    ReadResult,
    ReplyHeader,
    ReplyMarkup,
    ReportResult,
    ScheduledSent,
    ServiceAction,
    SponsoredHidden,
    SponsoredMessage,
    SuggestedPostState,
    SummaryResult,
    Tone,
    Transcription,
    Translation,
    ViewCount,
    WebPagePreview,
)
from tlgr.models.page import Page, PageInfo
from tlgr.models.peer import (
    Chat,
    Peer,
    PeerKind,
    PeerRef,
    PeerRefKind,
    Photo,
    Rights,
    User,
    UserRef,
    parse_message_link,
    parse_peer_ref,
    parse_user_ref,
)

__all__ = [
    "UNSET",
    "Button",
    "Chat",
    "ComposeResult",
    "DeleteResult",
    "Dialog",
    "DiceCatalog",
    "Draft",
    "DraftCleared",
    "EditResult",
    "Effect",
    "EntityReport",
    "ErrEnvelope",
    "ErrorBody",
    "EventEnvelope",
    "FactCheck",
    "Folder",
    "Forward",
    "ForwardedMessage",
    "GameInfo",
    "GameScore",
    "LinkResult",
    "MediaKind",
    "MediaSummary",
    "Message",
    "MessageEntity",
    "Meta",
    "Model",
    "NotifySettings",
    "OkEnvelope",
    "OpRequest",
    "Page",
    "PageInfo",
    "PaidMessageSettings",
    "Peer",
    "PeerKind",
    "PeerRef",
    "PeerRefKind",
    "Photo",
    "PinResult",
    "ReactResult",
    "ReactionSummary",
    "ReadReceipts",
    "ReadResult",
    "ReplyHeader",
    "ReplyMarkup",
    "ReportResult",
    "Request",
    "Rights",
    "ScheduledSent",
    "ServiceAction",
    "SponsoredHidden",
    "SponsoredMessage",
    "SuggestedPostState",
    "SummaryResult",
    "Tone",
    "Transcription",
    "Translation",
    "Unset",
    "User",
    "UserRef",
    "ViewCount",
    "WebPagePreview",
    "decode",
    "encode",
    "parse_message_link",
    "parse_peer_ref",
    "parse_user_ref",
    "to_builtins",
]
