#!/usr/bin/env python3
"""Generate `docs/reference/` from the registry.

Reference documentation that is written by hand is documentation that is
wrong: v1's README described flags three commands no longer had. Everything
under `docs/reference/` is therefore derived from the same `OperationSpec`
the Click command, the JSON Schema and the parity report come from, and
`tests/test_docs_fresh.py` fails when the checked-in files no longer match.

    python tools/gen_docs.py            # write docs/reference/*.md
    python tools/gen_docs.py --check    # exit 1 if anything is stale
    python tools/gen_docs.py --parity   # only PARITY.md
"""

from __future__ import annotations

import argparse
import sys
import typing
from pathlib import Path
from typing import Any

import msgspec

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import tlgr.ops  # noqa: E402,F401  — importing it populates the registry
from tlgr.cli.gen import _fields  # noqa: E402
from tlgr.parity import compute, render_table  # noqa: E402
from tlgr.registry import REGISTRY  # noqa: E402
from tlgr.schema import response_type_name  # noqa: E402

TARGET = ROOT / "docs" / "reference"

BANNER = "<!-- Generated by tools/gen_docs.py. Do not edit; edit the OperationSpec. -->"


def _type_label(field: Any) -> str:
    """A short, honest type for the flag table."""
    choices = field.cli.get("choices")
    if choices:
        return "|".join(choices)
    kind = field.cli.get("kind") or ""
    if kind:
        return {"peer": "chat", "user": "user", "msg_id": "msg-id"}.get(kind, kind)
    base = field.base
    if base is bool:
        return "flag"
    if base is int:
        return "int"
    if base is float:
        return "number"
    origin = typing.get_origin(base)
    if origin is typing.Literal:
        return "|".join(str(v) for v in typing.get_args(base))
    return "text"


def _flag_spelling(field: Any) -> str:
    flags = list(field.cli.get("flags") or [])
    if not flags:
        flags = ["--" + field.name.replace("_", "-")]
    if field.base is bool and (field.default is True or field.optional):
        negative = "--no-" + field.name.replace("_", "-")
        if not any("/" in flag for flag in flags):
            flags[0] = f"{flags[0]}/{negative}"
    return ", ".join(f"`{flag}`" for flag in flags)


def _describe(annotation: Any) -> str:
    if typing.get_origin(annotation) is typing.Annotated:
        for extra in typing.get_args(annotation)[1:]:
            if isinstance(extra, msgspec.Meta) and extra.description:
                return str(extra.description)
    return ""


def _usage(spec: Any, fields: list[Any]) -> str:
    parts = [f"tlgr {spec.cli_path}"]
    for field in sorted(
        (f for f in fields if f.cli.get("role") == "arg"), key=lambda f: int(f.cli.get("pos", 0))
    ):
        name = field.cli.get("metavar") or field.name.upper()
        if field.cli.get("variadic"):
            parts.append(f"[{name}]...")
        elif field.cli.get("required", True):
            parts.append(f"<{name}>")
        else:
            parts.append(f"[{name}]")
    if any(f.cli.get("role") != "arg" for f in fields) or True:
        parts.append("[OPTIONS]")
    return " ".join(parts)


def op_section(spec: Any) -> str:
    fields = _fields(spec.request)
    arguments = sorted(
        (f for f in fields if f.cli.get("role") == "arg"), key=lambda f: int(f.cli.get("pos", 0))
    )
    options = [f for f in fields if f.cli.get("role") != "arg"]

    out = [f"### `{spec.cli_path}`", "", spec.summary + ".", ""]
    if spec.description:
        out += [spec.description, ""]
    out += ["```", _usage(spec, fields), "```", ""]

    badges = []
    if spec.mutating:
        badges.append("mutating")
    if spec.destructive:
        badges.append("destructive (needs `--yes` off a TTY)")
    if spec.paginated is not None:
        badges.append(f"paginated (`{spec.paginated.value}` cursor)")
    if spec.idempotent:
        badges.append("idempotent (reports `already`)")
    if not spec.needs_account:
        badges.append("runs without an account")
    badges.append(f"returns `{response_type_name(spec)}`")
    out += ["**" + " · ".join(badges) + "**", ""]

    if arguments:
        out += ["| Argument | Type | Required | Meaning |", "|---|---|---|---|"]
        for field in arguments:
            name = field.cli.get("metavar") or field.name.upper()
            required = "yes" if field.cli.get("required", True) else "no"
            if field.cli.get("variadic"):
                required = "one or more" if field.cli.get("required", True) else "any number"
            out.append(
                f"| `{name}` | {_type_label(field)} | {required} | "
                f"{_describe(field.annotation) or '—'} |"
            )
        out.append("")

    if options:
        out += ["| Flag | Type | Default | Meaning |", "|---|---|---|---|"]
        for field in sorted(options, key=lambda f: f.name):
            default = field.default
            shown = "" if default in (None, "", [], (), False) else f"`{default}`"
            out.append(
                f"| {_flag_spelling(field)} | {_type_label(field)} | {shown} | "
                f"{_describe(field.annotation) or '—'} |"
            )
        out.append("")

    if spec.paginated is not None:
        out += [
            "Pagination is transport-level: `--limit/-n`, `--cursor TOKEN`, "
            "`--all` (walked inside the daemon, paced by the account's own "
            "rate limiter).",
            "",
        ]

    other = [name.replace(".", " ") for name in spec.names[1:]]
    if other:
        out += ["Also invocable as: " + ", ".join(f"`tlgr {name}`" for name in other), ""]

    out += ["```console", f"$ tlgr {spec.example_args} --json", "```", ""]

    if spec.covers or spec.covers_partial:
        covered = ", ".join(f"`{i}`" for i in spec.covers)
        partial = ", ".join(f"`{i}`" for i in spec.covers_partial)
        out.append(
            f"<details><summary>Catalog coverage ({len(spec.covers)} full, "
            f"{len(spec.covers_partial)} partial)</summary>\n"
        )
        if covered:
            out.append(f"Full: {covered}\n")
        if partial:
            out.append(f"Partial: {partial}\n")
        if spec.coverage_note:
            out.append(f"{spec.coverage_note}\n")
        out.append("</details>\n")
    return "\n".join(out)


def group_page(group: str) -> str:
    specs = sorted((s for s in REGISTRY.values() if s.group == group), key=lambda s: s.id)
    lines = [
        BANNER,
        "",
        f"# `tlgr {group}`",
        "",
        f"{len(specs)} operation{'s' if len(specs) != 1 else ''}. Every one takes the global "
        "flags (`--json`, `--plain`, `-a/--account`, `--results-only`, `--select`, "
        "`--dry-run`, `--yes`, `--no-input`, `--flood-wait-max`, `-v`) anywhere on "
        "the line.",
        "",
        "| Command | Summary |",
        "|---|---|",
    ]
    for spec in specs:
        anchor = spec.cli_path.replace(" ", "-")
        lines.append(f"| [`{spec.cli_path}`](#tlgr-{anchor}) | {spec.summary} |")
    lines.append("")
    for spec in specs:
        lines.append(op_section(spec))
    return "\n".join(lines).rstrip() + "\n"


def parity_page() -> str:
    report = compute()
    lines = [
        BANNER,
        "",
        "# Feature parity",
        "",
        "Coverage against the Telegram feature catalog, computed from the "
        "registry: every operation declares the catalog ids it covers, and "
        "`tlgr.parity` subtracts them from the index shipped in the package. "
        "Regenerate with `make parity`.",
        "",
        "`covered` is implemented today. `acct%` is covered **plus** waived — "
        "an id this build genuinely cannot cover, named in "
        "`tlgr/data/parity_waivers.toml` with the reason and the MTProto "
        "method that is missing. Ids whose feasibility is `not-applicable` or "
        "`prohibited` are excluded from the denominator once and never "
        "counted again.",
        "",
        "```",
        render_table(report),
        "```",
        "",
        "## By domain",
        "",
        "| Domain | Covered | Required | % | Accounted % | Ops |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for domain, stats in report.by_domain.items():
        lines.append(
            f"| `{domain}` | {stats['covered']} | {stats['required']} | "
            f"{stats['percent']}% | {stats['accounted_percent']}% | {stats['ops']} |"
        )
    lines += [
        "",
        "## By priority",
        "",
        "| Priority | Covered | Required | % | Accounted % |",
        "|---|---:|---:|---:|---:|",
    ]
    for priority, stats in report.by_priority.items():
        lines.append(
            f"| {priority} | {stats['covered']} | {stats['required']} | "
            f"{stats['percent']}% | {stats['accounted_percent']}% |"
        )

    if report.partial:
        lines += [
            "",
            "## Partial coverage",
            "",
            "| Catalog id | Operation | Why partial |",
            "|---|---|---|",
        ]
        for item in report.partial:
            lines.append(f"| `{item['id']}` | `{item['op']}` | {item['note'] or '—'} |")

    migrated = [
        domain
        for domain, stats in report.by_domain.items()
        if stats["covered"] and stats["percent"] > 50
    ]
    lines += [
        "",
        "## What this build cannot do",
        "",
        "Every one of these is registered as a command that exits 13 "
        '(`NOT_SUPPORTED`) naming the method it needs, so "unavailable in '
        'this build" is a different answer from "no such command":',
        "",
        "| Catalog id | Priority | Feature | Why |",
        "|---|---|---|---|",
    ]
    for item in report.uncovered:
        if item["domain"] not in migrated:
            continue
        lines.append(f"| `{item['id']}` | {item['priority']} | {item['name']} | {item['reason']} |")
    return "\n".join(lines).rstrip() + "\n"


def index_page(groups: list[str]) -> str:
    lines = [
        BANNER,
        "",
        "# Command reference",
        "",
        f"{len(REGISTRY)} operations across {len(groups)} groups, generated from the "
        "operation registry. Groups still served by v1's hand-written commands are "
        "not listed here; they arrive with their own PR.",
        "",
        "| Group | Operations | Reference |",
        "|---|---:|---|",
    ]
    for group in groups:
        count = sum(1 for spec in REGISTRY.values() if spec.group == group)
        lines.append(f"| `{group}` | {count} | [{group}.md]({group}.md) |")
    lines += [
        "",
        "- [PARITY.md](PARITY.md) — coverage against the Telegram feature catalog.",
        "- `tlgr schema --json` — the same information as JSON Schema draft 2020-12.",
        "",
    ]
    return "\n".join(lines).rstrip() + "\n"


def generate() -> dict[Path, str]:
    groups = sorted({spec.group for spec in REGISTRY.values()})
    pages = {TARGET / f"{group}.md": group_page(group) for group in groups}
    pages[TARGET / "PARITY.md"] = parity_page()
    pages[TARGET / "README.md"] = index_page(groups)
    return pages


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if anything is stale.")
    parser.add_argument("--parity", action="store_true", help="Only regenerate PARITY.md.")
    args = parser.parse_args(argv)

    pages = generate()
    if args.parity:
        pages = {path: text for path, text in pages.items() if path.name == "PARITY.md"}

    stale = []
    for path, text in pages.items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current == text:
            continue
        stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")

    if args.check:
        if stale:
            names = ", ".join(str(p.relative_to(ROOT)) for p in stale)
            print(f"stale: {names}\nrun: make docs", file=sys.stderr)
            return 1
        print(f"{len(pages)} reference pages are current")
        return 0
    print(f"wrote {len(stale)} of {len(pages)} reference pages into {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
